export const data = [
    {
        id: 1,
		name: 'Blue/Red Dinosaur Long Sleeve Baby',
		searchTerm: 'Bodysuits',
		price: 43,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/U48684s.jpg',
    },
    {
        id: 2,
		name: 'Pink and Mint Green Baby Bodysuits',
		searchTerm: 'Bodysuits',
		price: 36,
		image: 'https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G63/shotview-315x472/4905/U17-346s.jpg',
    },
    {
        id: 3,
		name: 'Soft Touch Fleece All-In-One',
		searchTerm: 'Bodysuits',
		price: 63,
		image: 'https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G65/shotview-315x472/4603/A87-711s.jpg',
    },
    {
        id: 4,
		name: 'Baby Long Sleeve Bodysuits',
		searchTerm: 'Bodysuits',
		price: 32,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/T77299s.jpg',
    },
    {
        id: 5,
		name: 'Laura Ashley Ruffle Neck Cord Dress',
		searchTerm: 'Dresses',
		price: 77,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/T83226s.jpg',
    },
    {
        id: 6,
		name: 'Laura Ashley Embroidered Smock Dress',
		searchTerm: 'Dresses',
		price: 82,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/C45807s4.jpg',
    },
    {
        id: 7,
		name: 'Boden Blue Tulle Party Dress',
		searchTerm: 'Dresses',
		price: 90,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/C00094s.jpg',
    },
    {
        id: 8,
		name: 'Baker by Ted Baker Pink Ponte Dress',
		searchTerm: 'Dresses',
		price: 69,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/U09106s.jpg',
    },
    {
        id: 9,
		name: 'Myleene Klass Baby Printed Snowsuit',
		searchTerm: 'Coats, Jackets & Pramsuits',
		price: 97,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/M95613s.jpg',
    },
    {
        id: 10,
		name: 'Cord Baby Borg Lined Hooded Jacket',
		searchTerm: 'Coats, Jackets & Pramsuits',
		price: 50,
		image: 'https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G63/shotview-315x472/249/A81-613s.jpg',
    },
    {
        id: 11,
		name: 'Myleene Klass Baby Printed Snowsuit',
		searchTerm: 'Coats, Jackets & Pramsuits',
		price: 97,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/M95623s.jpg',
    },
    {
        id: 12,
		name: 'Lightweight Jersey Baby Jacket',
		searchTerm: 'Coats, Jackets & Pramsuits',
		price: 36,
		image: 'https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G55/shotview-315x472/4908/U04-202s.jpg',
    },
    {
        id: 13,
		name: 'Baby 2 Pack Turban Hats',
		searchTerm: 'Accessories',
		price: 17,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/372486s.jpg',
    },
    {
        id: 14,
		name: 'Knitted Baby Pom Hat',
		searchTerm: 'Accessories',
		price: 14,
		image: 'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/T60441s.jpg',
    },
    {
        id: 15,
		name: 'Baby Weaning And Feeding Sleeved Bib',
		searchTerm: 'Accessories',
		price: 20,
		image: 'https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G63/shotview-315x472/4922/T99-571s.jpg',
    },
    {
        id: 16,
		name: 'Knitted Baby Pom Hat',
		searchTerm: 'Accessories',
		price: 14,
		image: 'https://xcdn.next.co.uk/common/Items/Default/Default/Publications/G55/shotview-315x472/4907/M92-000s.jpg',
    }
]